### ISSUE TITLE
Let it lay here

### ISSUE THREAD

**Issue by Ygarr** [Murph9/Jetris#1]
![jetris2022-09-11_17-23](https://user-images.githubusercontent.com/14309871/189532721-26c4045f-2ea8-4c6f-8fe4-4269d205201f.png)

**Comment by Murph9** [comment]
What is this specific issue:
- Is it the button that slightly overlapping?
- the `Single` word under the start and quit buttons
- or or the background dots doing something funky?

**Comment by Ygarr** [comment]
Think just in-game shot preview to add, first of all.
Overlapping button also. :)

Other things not critical as for opensource

**Comment by Murph9** [comment]
Okay cool
